#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/Function/import
source ${Path}/Function/returnError

InstallList=(
  "package"
  "uv"
  "gitclone"
)

for i in ${InstallList[@]}
do
  if ! bash ${Path}/Install/${i}
  then
    returnError
    exit
  fi
done
cp -f ${Path}/start /usr/local/bin/afab
sed -i "s|AstrBot_Shell_Home|${Path}|g" /usr/local/bin/afab
chmod +x /usr/local/bin/afab
afab