#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/Function/import
source ${Path}/Function/returnError

InstallList=(
  "package"
  "pip"
  "gitclone"
)

for i in ${InstallList[@]}
do
  if ! bash ${Path}/Install/${i}
  then
    returnError
    exit
  fi
done
ln -sf ${Path}/start /usr/local/bin/afab
chmod +x /usr/local/bin/afab
afab