#!/bin/env bash
import setColour
function setMsgboxSize(){
local HEIGHT=$(($(tput lines) - 15))
local WIDTH=$(($(tput cols) - 5))
if (( $HEIGHT <= 0 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕高度过低.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
if (( $WIDTH <= 0 ));then
  echo -e ${blue}[${red}*${blue}] ${cyan}您的屏幕宽度过窄.${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}考虑缩小终端字体.${background}
  exit
fi
echo ${HEIGHT} ${WIDTH}
}