#!/bin/env bash
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
export GHP="https://gh.arcticfox.top/"
function log.info(){
    local timestamp=$(date +"%H:%M:%S")
    echo -e "${BLUE}[INFO][${timestamp}] - $1${NC}"
}
function log.success(){
    local timestamp=$(date +"%H:%M:%S")
    echo -e "${GREEN}[SUCCESS][${timestamp}] - $1${NC}"
}
function log.warn(){
    local timestamp=$(date +"%H:%M:%S")
    echo -e "${YELLOW}[WARN][${timestamp}] - $1${NC}"
}
function log.error(){
    local timestamp=$(date +"%H:%M:%S")
    echo -e "${RED}[ERROR][${timestamp}] - $1${NC}" >&2
}
function IncrCounter(){
  if [ -z ${count} ]
  then
    count=0
  fi
  ((count++))
  case ${count} in
    3)
      count=0
      return 1
  esac
  return 0
}
function getFile(){
file="$1"
URL="$2"
Download(){
  log.info "正在下载 ${file}"
  until ${Command}
  do
    if ! IncrCounter
    then
      log.error "错误次数过多"
      return 1
    fi
    log.warn "下载失败 三秒后重试"
    sleep 3s
  done
  log.success "下载完成"
  return 0
}
if $(command -v wget > /dev/null 2>&1) && $(wget --help | grep -q show-progress)
then
  Command="wget --quiet --show-progress --output-document="${file}" --continue "${URL}""
  Download
elif $(command -v curl > /dev/null 2>&1) && $(curl --help all | grep -q progress-bar)
then
  Command="curl --output "${file}" --progress-bar --location --continue-at - "${URL}""
  Download
elif $(command -v wget > /dev/null 2>&1)
then
  Command="wget --output-document="${file}" --continue "${URL}""
  Download
else
  log.error "无下载器"
  return 1
fi
}
function getLocation(){
selectLocation(){
echo
echo -en "
 ———————————————————
 ${cyan}请问您的设备所在位置是? 
    ${green}1${white}. 中国大陆 ${background}
    ${green}2${white}. 其他位置 ${background}
 ———————————————————
 ${cyan}请输入数字 ${white}[1-2]: ${background}"
read num
case "$num" in
  1)
    return 0;;
  2)
    return 1;;
  *)
    log.warn "输入错误 保持默认 中国大陆"
    return 0
esac
}
Json=$(curl -sL --connect-timeout 5 --max-time 10 ipinfo.io/json)
if [ -n "${Json}" ]
then
  if ! echo "${Json}" | grep -q error
  then
    if echo "${Json}" | jq -r .country | grep -q "CN"; then
      return 0
    else
      return 1
    fi
  fi
fi
Json=$(curl -sL --connect-timeout 5 --max-time 10 ip-api.com/json)
if [ -n "${Json}" ]
then
  if ! echo "${Json}" | grep -q fail
  then
    if echo "${Json}" | jq -r .countryCode | grep -q "CN"; then
      return 0
    else
      return 1
    fi
  fi
fi
selectLocation
local result=$?
return ${result}
}
function getArchitecture(){
  local machine=$(uname -m)
  case $machine in
    x86_64|x64)
      echo x86_64
      ;;
    aarch64|arm64)
      echo aarch64
      ;;
    *)
      log.error "不支持的架构"
      log.warn "您的CPU为 $(uname -m)"
      log.warn "请截图以便于开发者适配"
      returnError
      ;;
  esac
}
function gitCR(){
gitClone(){
if getLocation
then
  if ! git clone --depth=1 ${GHP}https://github.com/$1
  then
    returnError
  fi
else
  if ! git clone --depth=1 https://github.com/$1
  then
    returnError
  fi
fi
}
gitRelease(){
if getLocation
then
  if ! getFile $1 ${GHP}https://github.com/$2/releases/latest/download/$3
  then
    returnError
  fi
else
  if ! getFile $1 https://github.com/$2/releases/latest/download/$3
  then
    returnError
  fi
fi
}
case $1 in
clone)
  gitClone $2;;
release)
  gitRelease $2 $3 $4;;
esac
}