#!/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")./function"
if [ ! "$(uname -o)" == "Android" ];then
  echo -e ${blue}[${red}*${blue}] ${cyan}错误 ${yellow}非Android 无法运行${background}
fi

cd $HOME
if [ ! -d $HOME/AF-Proot ];then
  mkdir AF-Proot
fi
cd AF-Proot

#详见 https://mirrors.cernet.edu.cn/lxc-images
Linux="ubuntu"
Version="noble"
Arch="arm64"
Variant="default"
FOLDER="${Linux}-${Version}"

URL="https://mirrors.cernet.edu.cn/lxc-images/images/${Linux}/${Version}/${Arch}/${Variant}/"
log.info "正在获取 构建日期"
BuildDate=$(curl -sL ${URL} | grep 'class="link"><a href="' | grep -oE 'title="[^"]+"' | grep -oE '[^"]+' | tail -n 1)
if [ -z ${date} ];then
  log.error "构建日期为空"
  log.warn "镜像: $(curl -s ${URL} | grep -oP 'https?://\K[^/]+')"
  exit
fi

URL="https://mirrors.cernet.edu.cn/lxc-images/images/${Linux}/${Version}/${Arch}/${Variant}/${BuildDate}/rootfs.tar.xz"
getFile rootfs.tar.xz ${URL}
log.info "开始解压 镜像文件"
if pv rootfs.tar.xz | proot --link2symlink tar -xJf - -C $HOME/AF-Proot/${FOLDER} > /dev/null 2>&1 ||:
then
  log.success "解压成功"
else
  log.error "解压失败"
fi

URL