#!/bin/env bash
source function




if [ ! "$(uname -o)" == "Android" ];then
  echo -e ${blue}[${red}*${blue}] ${cyan}错误 ${yellow}非Android 无法运行${background}
fi
URL="https://mirrors.cernet.edu.cn/lxc-images/images/ubuntu/noble/arm64/default/"
echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}镜像日期${background}
date=$(curl -sL ${URL} | grep 'class="link"><a href="' | grep -oE 'title="[^"]+"' | grep -oE '[^"]+' | tail -n 1)
if [ -z ${date} ];then
  echo -e ${blue}[${red}*${blue}] ${cyan}错误 ${yellow}日期为空${background}
  echo -e ${blue}[${red}*${blue}] ${cyan}镜像 ${yellow}$(curl -s ${URL} | grep -oP 'https?://\K[^/]+')${background}
  exit
fi
URL="https://mirrors.cernet.edu.cn/lxc-images/images/ubuntu/noble/arm64/default/${date}/rootfs.tar.xz"
getFile rootfs.tar.xz ${URL}

