#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/../function/import

import log
import gitCR
import getFile
import setColour
import getLocation

log.info "正在克隆 AstrBot"
if gitCR clone master AstrBotDevs/AstrBot
then
  log.success "克隆成功"
else
  log.error "克隆失败"
  returnError
fi
cd AstrBot
gitCR release dist.zip AstrBotDevs/AstrBot dist.zip
if [ ! -d data ]
then
  mkdir data
fi
log.info "正在解压 面板文件"
size=$(unzip -l dist.zip | wc -l)
size=$(expr ${size} - 4)
if unzip dist.zip -d data/ | pv -l -s ${size} > /dev/null
then
  rm -rvf dist.zip
else
  log.error "解压失败"
  returnError
fi
log.info "正在安装 依赖文件"
if uv sync
then
  log.success "依赖安装成功"
else
  log.error "依赖安装失败"
  returnError
fi