#!/bin/env bash
import getLocation
import setColour
import getFile
import getArchitecture
import returnError
import gitCR
import log
echo -e ${blue}[${green}*${blue}] ${cyan}开始安装 ${yellow}UV${background}
log.info "开始安装 UV包管理器"
gitCR release UV.tar.gz astral-sh/uv uv-$(getArchitecture)-unknown-linux-gnu.tar.gz
${UVURL}
mkdir UVdir
if ! pv UV.tar.gz | tar -zxf - -C UVdir
then
  log.error "解压失败"
  returnError
fi
mv UVdir/$(ls UVdir) /usr/local/UV
rm -rvf UVdir UV.tar.gz
rm -rf /usr/local/UV > /dev/null 2>&1
echo '
#Python.UV
export PATH=$PATH:/usr/local/UV
' >> /etc/profile
export PATH=$PATH:/usr/local/UV
mkdir -p $HOME/.config/uv/
echo '
[[index]]
url = "https://mirrors.cernet.edu.cn/pypi/web/simple"
default = true
' > $HOME/.config/uv/uv.toml