#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/../Function/import

import log
import gitCR
import getFile
import getLocation
import getArchitecture

if [ -x "$(command -v uv)" ]
then
  log.info "UV包管理器 已安装"
  exit 0
else
  rm -rf /usr/local/UV > /dev/null 2>&1
fi
log.info "开始安装 UV包管理器"
if ! gitCR release UV.tar.gz astral-sh/uv uv-$(getArchitecture)-unknown-linux-gnu.tar.gz
then
  returnError
fi
mkdir UVdir
log.info "正在解压 UV.tar.gz"
if pv UV.tar.gz | tar -zxf - -C UVdir
then
  log.success "解压成功"
else
  log.error "解压失败"
  exit 1
fi
mv UVdir/$(ls UVdir) /usr/local/UV
rm -rvf UVdir UV.tar.gz
if ! grep -q "Python.UV" /etc/profile
then
echo '
#Python.UV
export PATH=$PATH:/usr/local/UV
' >> /etc/profile
fi
export PATH=$PATH:/usr/local/UV
mkdir -p $HOME/.config/uv/
echo '
[[index]]
url = "https://mirrors.cernet.edu.cn/pypi/web/simple"
default = true
' > $HOME/.config/uv/uv.toml
source /etc/profile