#!/bin/env bash
import setMenuSize
import setMsgboxSize
import setTUISoftware

Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
# CP: Config Path
CP="../config.json"
# TM: Terminal Multiplexer
TM="$(jq -r .TerminalMultiplexer ${Path}/${CP})"
# TT: Title Text
TT="$(jq -r .TitleText ${Path}/${CP})"
# SN: Session Name
SN="$(jq -r .SessionName ${Path}/${CP})"
# SC: Start Command
SC="$(jq -r .StartCommand ${Path}/${CP})"

function MainMenu(){
Number=$($(setTUISoftware) \
--title "$TT" \
--menu "请选择操作: " \
$(setMenuSize) \
"1" "启动运行" \
"2" "前台启动" \
"3" "停止运行" \
"4" "重新启动" \
"5" "打开日志" \
"6" "全部更新" \
"7" "其他功能" \
"8" "进入bash" \
"0" "退出菜单" \
3>&1 1>&2 2>&3)
case ${Number} in
startBackground)
    source ${Path}/AppFun/startApp SBG
  ;;
startForeground)
    source ${Path}/AppFun/startApp SFG
  ;;
stopBot)
    source ${Path}/AppFun/stopApp
  ;;
restartBot)
    source ${Path}/AppFun/restartApp
  ;;
openLog)
    source ${Path}/AppFun/logApp
  ;;
updateAll)
    source ${Path}/updateAll
  ;;
otherFunction)
    $(setTUISoftware) --title "$TT"  \
    --msgbox "未完工" \
    $(setMsgboxSize)
    #source ${Path}/otherFunction
  ;;
enterBash)
    exec bash
  ;;
exitMenu)
    return 2
  ;;
esac
}
while true
do
  MainMenu
  case $? in
  2)
    exit
  esac
done