#!/bin/env bash
import setColour
import setMenuSize
import setMsgboxSize
import setTUISoftware
import manageSession
TitleText=AstrBot-Shell

function startBackground(){
if manageSession list ${TitleText}
then
  if $(setTUISoftware) --title "${TitleText}"  \
  --yesno "${TitleText} [已经启动]" \
  --yes-button "打开日志" --no-button "返回菜单" \
  $(setMsgboxSize)
  then
    manageSession log ${TitleText}
  else
    return
  fi
else
  if [ -e data/cmd_config.json ]
  then
    port=$(jq -r .dashboard.port data/cmd_config.json)
  else
    port=6185
  fi
  if curl -sL http://localhost:${port}
  then
    $(setTUISoftware) --title "${TitleText}"  \
    --msgbox "${TitleText} 目前处于 [前台]" \
    $(setMsgboxSize)
    return
  fi
  manageSession start "${TitleText}" "uv run main.py"
  {
    i=0
    until curl -sL http://localhost:${port}
    do
      echo $i
      sleep 0.05
      ((i++))
    done
    echo 100
    sleep 0.1
  } | $(setTUISoftware) --gauge "正在启动 [${TitleText}]" \
  $(setMsgboxSize)
  if $(setTUISoftware) --title "${TitleText}"  \
  --yesno "${TitleText} [已经启动]" \
  --yes-button "打开日志" --no-button "返回菜单" \
  $(setMsgboxSize)
  then
    manageSession log ${TitleText}
  else
    return
  fi
fi
}