#!/bin/env bash
import setColour
import setMenuSize
import setMsgboxSize
import setTUISoftware
import manageSession
TitleText=AstrBot-Shell

function stopBot(){
if manageSession list ${TitleText}
then
  manageSession stop ${TitleText}
  if [ -e data/cmd_config.json ]
  then
    port=$(jq -r .dashboard.port data/cmd_config.json)
  else
    port=6185
  fi
  {
    i=0
    until curl -sL http://localhost:${port}
    do
      echo $i
      sleep 0.05
      ((i++))
    done
    echo 100
    sleep 0.1
  } | $(setTUISoftware) --gauge "正在停止 [${TitleText}]" \
  $(setMsgboxSize)
  $(setTUISoftware) --title "${TitleText}"  \
  --msgbox "${TitleText} [停止成功]" \
  $(setMsgboxSize)
else
  if [ -e data/cmd_config.json ]
  then
    port=$(jq -r .dashboard.port data/cmd_config.json)
  else
    port=6185
  fi
  if curl -sL http://localhost:${port}
  then
    PID=$(ps all | grep "uv run main.py" | sed '/grep/d' | awk '{print $3}')
    if [ -n ${PID} ];then
      kill -9 ${PID}
      return
    fi
  fi
  $(setTUISoftware) --title "${TitleText}"  \
  --msgbox "${TitleText} [没有启动]" \
  $(setMsgboxSize)
fi
}