#!/bin/env bash
import setColour

echo -e ${blue}[${green}*${blue}] ${cyan}正在更新 ${yellow}AstrBot${background}
if ! git pull
then
  returnError
fi
echo -e ${blue}[${green}*${blue}] ${cyan}正在更新 ${yellow}依赖${background}
if ! source venv/bin/activate && python3.10 -m pip install -r requirements.txt
then
  returnError
fi
echo -ne ${blue}[${green}*${blue}] ${cyan}更新完成 ${yellow}回车返回${background};read
